# Generated by Django 5.1.6 on 2025-04-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shippingprice',
            new_name='shippingPrice',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='taxprice',
            new_name='taxPrice',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='totalprice',
            new_name='totalPrice',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='Product',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/sample.jpg', null=True, upload_to=''),
        ),
    ]
