# Generated by Django 5.2 on 2025-05-12 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_review_createdat_alter_shippingaddress_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Product',
            new_name='product',
        ),
    ]
